services:
  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "8080:80"
    # depends_on:
    #   - backend
    networks:
      - app-network


  backend:
    build: ./backend
    container_name: backend
    ports:
      - "8002:8002"
    volumes:
      - ./backend:/app 
    networks:
      - app-network
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}  # Passing OPENAI_API_KEY env variable

networks:
  app-network:
    driver: bridge
