name: Deploy FastAPI to Server

on:
  push:
    branches:
      - development

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Deploy via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}       # Server IP
          username: ${{ secrets.SSH_USER }}   # e.g., 'ubuntu'
          key: ${{ secrets.SSH_KEY }}         # Private key
          script: |
            # Navigate directly to the project repository on the server
            cd food_reciept_agent

            # Pull the latest code
            git pull origin development

            # Rebuild and restart Docker Compose
            docker-compose down
            docker-compose up -d --build
